In [2]:
import keras
import numpy as np
import pandas as pd
import cv2
from matplotlib import pyplot as plt
from keras.models import Sequential 
from keras.layers import Conv2D,MaxPooling2D, Dense,Flatten, Dropout
from keras.datasets import mnist 
import matplotlib.pyplot as plt
from keras.utils import np_utils
from keras.optimizers import SGD
import os

In [3]:
train = pd.read_csv('sign_mnist_train.csv')
test = pd.read_csv('sign_mnist_test.csv')

In [4]:
train.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,3,107,118,127,134,139,143,146,150,153,...,207,207,207,207,206,206,206,204,203,202
1,6,155,157,156,156,156,157,156,158,158,...,69,149,128,87,94,163,175,103,135,149
2,2,187,188,188,187,187,186,187,188,187,...,202,201,200,199,198,199,198,195,194,195
3,2,211,211,212,212,211,210,211,210,210,...,235,234,233,231,230,226,225,222,229,163
4,13,164,167,170,172,176,179,180,184,185,...,92,105,105,108,133,163,157,163,164,179

In [5]:
test.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,6,149,149,150,150,150,151,151,150,151,...,138,148,127,89,82,96,106,112,120,107
1,5,126,128,131,132,133,134,135,135,136,...,47,104,194,183,186,184,184,184,182,180
2,10,85,88,92,96,105,123,135,143,147,...,68,166,242,227,230,227,226,225,224,222
3,0,203,205,207,206,207,209,210,209,210,...,154,248,247,248,253,236,230,240,253,255
4,3,188,191,193,195,199,201,202,203,203,...,26,40,64,48,29,46,49,46,46,53

In [6]:
y_train = train['label'].values
y_test = test['label'].values

X_train = train.drop(['label'],axis=1)
X_test = test.drop(['label'], axis=1)

X_train = np.array(X_train.iloc[:,:])
X_train = np.array([np.reshape(i, (28,28)) for i in X_train])

X_test = np.array(X_test.iloc[:,:])
X_test = np.array([np.reshape(i, (28,28)) for i in X_test])

num_classes = 26
y_train = np.array(y_train).reshape(-1)
y_test = np.array(y_test).reshape(-1)

y_train = np.eye(num_classes)[y_train]
y_test = np.eye(num_classes)[y_test]

In [7]:
X_train = X_train.reshape((27455, 28, 28, 1))
X_test = X_test.reshape((7172, 28, 28, 1))

In [8]:
classifier = Sequential()
classifier.add(Conv2D(filters=8, kernel_size=(3,3),strides=(1,1),padding='same',input_shape=(28,28,1),activation='relu', data_format='channels_last'))
classifier.add(MaxPooling2D(pool_size=(2,2)))
classifier.add(Conv2D(filters=16, kernel_size=(3,3),strides=(1,1),padding='same',activation='relu'))
classifier.add(Dropout(0.5))
classifier.add(MaxPooling2D(pool_size=(4,4)))
classifier.add(Dense(128, activation='relu'))
classifier.add(Flatten())
classifier.add(Dense(26, activation='softmax'))
classifier.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:From B:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From B:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.

In [9]:
classifier.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
classifier.fit(X_train, y_train, epochs=25, batch_size=100)

WARNING:tensorflow:From B:\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/25
27455/27455 [==============================] - 10s 355us/step - loss: 6.4482 - acc: 0.2317
Epoch 2/25
27455/27455 [==============================] - 9s 340us/step - loss: 1.1142 - acc: 0.6373
Epoch 3/25
27455/27455 [==============================] - 9s 342us/step - loss: 0.6560 - acc: 0.7769
Epoch 4/25
27455/27455 [==============================] - 9s 345us/step - loss: 0.4082 - acc: 0.8574
Epoch 5/25
27455/27455 [==============================] - 9s 345us/step - loss: 0.2895 - acc: 0.8991
Epoch 6/25
27455/27455 [==============================] - 9s 339us/step - loss: 0.2311 - acc: 0.9207
Epoch 7/25
27455/27455 [==============================] - 9s 335us/step - loss: 0.1813 - acc: 0.9377
Epoch 8/25
27455/27455 [==============================] - 9s 335us/step - loss: 0.1664 - acc: 0.9429
Epoch 9/25
27455/27455 [==============================] - 10s 362us/step - loss: 0.1301 - acc: 0.9568
Epoch 10/25
27455/27455 [==============================] - 10s 370us/step - loss: 0.1220 - acc: 0.9580
Epoch 11/25
27455/27455 [==============================] - 9s 345us/step - loss: 0.1077 - acc: 0.9634
Epoch 12/25
27455/27455 [==============================] - 10s 381us/step - loss: 0.0982 - acc: 0.9662
Epoch 13/25
27455/27455 [==============================] - 10s 380us/step - loss: 0.0887 - acc: 0.9698
Epoch 14/25
27455/27455 [==============================] - 11s 384us/step - loss: 0.0784 - acc: 0.9736
Epoch 15/25
27455/27455 [==============================] - 10s 359us/step - loss: 0.0803 - acc: 0.9725
Epoch 16/25
27455/27455 [==============================] - 10s 348us/step - loss: 0.0724 - acc: 0.9755
Epoch 17/25
27455/27455 [==============================] - 9s 342us/step - loss: 0.0735 - acc: 0.9763
Epoch 18/25
27455/27455 [==============================] - 9s 335us/step - loss: 0.0707 - acc: 0.9762
Epoch 19/25
27455/27455 [==============================] - 9s 340us/step - loss: 0.0605 - acc: 0.9800
Epoch 20/25
27455/27455 [==============================] - 10s 369us/step - loss: 0.0516 - acc: 0.9825
Epoch 21/25
27455/27455 [==============================] - 11s 391us/step - loss: 0.0700 - acc: 0.9772
Epoch 22/25
27455/27455 [==============================] - 10s 371us/step - loss: 0.0612 - acc: 0.9799
Epoch 23/25
27455/27455 [==============================] - 11s 395us/step - loss: 0.0576 - acc: 0.9811
Epoch 24/25
27455/27455 [==============================] - 11s 416us/step - loss: 0.0540 - acc: 0.9819
Epoch 25/25
27455/27455 [==============================] - 10s 362us/step - loss: 0.0523 - acc: 0.9821

In [10]:
accuracy = classifier.evaluate(x=X_test,y=y_test,batch_size=32)
print("Accuracy: ",accuracy[1])

7172/7172 [==============================] - 1s 188us/step
Accuracy:  0.9170384829894033

In [11]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d_1 (Conv2D)            (None, 28, 28, 8)         80
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 8)         0
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 14, 16)        1168
_________________________________________________________________
dropout_1 (Dropout)          (None, 14, 14, 16)        0
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 3, 3, 16)          0
_________________________________________________________________
dense_1 (Dense)              (None, 3, 3, 128)         2176
_________________________________________________________________
flatten_1 (Flatten)          (None, 1152)              0
_________________________________________________________________
dense_2 (Dense)              (None, 26)                29978
=================================================================
Total params: 33,402
Trainable params: 33,402
Non-trainable params: 0
_________________________________________________________________

In [13]:
classifier.save('CNNmodel.h5')